spring.application.name=storelocator
spring.datasource.url=jdbc:mysql://localhost:3306/storelocator_db
spring.datasource.username=root
spring.datasource.password=Rashitha@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
logging.level.org.springframework.web=DEBUG